restore optionality of -i's argument in ssh-copy-id "install script"
(adaptation)

diff --git a/contrib/ssh-copy-id b/contrib/ssh-copy-id
--- a/contrib/ssh-copy-id
+++ b/contrib/ssh-copy-id
@@ -118,7 +118,9 @@ FORCED=false
 DRY_RUN=false
 OPTS_oF=
 SSH_PORT=
-while getopts "i:o:p:F:t:fnsxh?" OPT
+OPTS="io:p:F:t:fnsxh?"
+
+while getopts "$OPTS" OPT
 do
   case "$OPT" in
     i)
@@ -127,6 +129,19 @@ do
         usage
       fi
       SEEN_OPT_I=yes
+
+      # Check for -i's optional parameter
+      eval "nextarg=\${$OPTIND}"
+      if test $OPTIND = $# ; then
+        if test -r "$nextarg" && grep -iq ssh "$nextarg"; then
+          printf '\n%s: ERROR: Missing hostname. Use "-i -- %s" if you really mean to use this as the hostname\n\n' "$0" "$nextarg" >&2
+          usage
+        fi
+      elif ! expr -- "$nextarg" : "-[$(echo "$OPTS" | tr -d :)-]" >/dev/null ; then
+        # when not at the last arg, and not followed by an option, -i has an argument
+        OPTARG="$nextarg"
+        OPTIND=$((OPTIND + 1))
+      fi
       use_id_file "${OPTARG:-$DEFAULT_PUB_ID_FILE}"
       ;;
     o|F)
